### ISSUE TITLE
Error in /api/search/city

### ISSUE THREAD

**Issue by elizabethtl** [Sanayshah2/CityByte#18]
**error message**
Traceback (most recent call last):
  File "/home/etlin/Documents/ncsu/fall2022_csc510/citybyte-venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/etlin/Documents/ncsu/fall2022_csc510/citybyte-venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/etlin/Documents/ncsu/fall2022_csc510/citybyte-venv/lib/python3.10/site-packages/django/views/decorators/http.py", line 43, in inner
    return func(request, *args, **kwargs)
  File "/home/etlin/Documents/ncsu/fall2022_csc510/CityByte/search/views.py", line 19, in city_suggestions
    suggestions_data = GenericDBSearchAutoCompleteHelper(
  File "/home/etlin/Documents/ncsu/fall2022_csc510/CityByte/search/helpers/autocomplete.py", line 25, in get_suggestions
    return self._search_util.get_city_suggestions(city=city, **kwargs)
  File "/home/etlin/Documents/ncsu/fall2022_csc510/CityByte/search/utils/search.py", line 67, in get_city_suggestions
    self._access_token = response.json()["access_token"]
KeyError: 'access_token'

**To Reproduce**
start server with `python manage.py runserver`

**Expected behavior**
search should return results
but no results shown

**Comment by sshah3420** [comment]
This likely has the same cause as #16 . Am looking into it

**Comment by elizabethtl** [comment]
solved issue, had to do with API key
